version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: '@vercel/ncc'
        versions: ['0.38.*']
    groups:
      types:
        patterns:
          - '@types/*'
      development-dependencies:
        dependency-type: 'development'
        exclude-patterns:
          - '@types/*'
      actions:
        patterns:
          - '@actions/*'
    reviewers:
      - catchen
    assignees:
      - catchen
    labels:
      - accept2ship

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - catchen
    labels:
      - pass2ship
