name: "ESLint Suggestion"
description: "Pull Request Suggestions from ESLint"
inputs:
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  github-workspace:
    description: "Path to the repo directory"
    required: true
  eslint-path:
    description: "Path to the eslint binary file"
    required: false
    default: "node_modules/.bin/eslint"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "plus-square"
  color: "blue"
