name: "ESLint Suggestion"
description: "Pull Request Suggestions from ESLint"
inputs:
  github-token:
    description: "GitHub token"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
