name: "ESLint Suggestion"
description: "Pull Request Suggestions from ESLint"
inputs:
  request-changes:
    description: "Request changes if ESLint doesn't pass."
    required: false
    default: true
  fail-check:
    description: "Fail the workflow and its corresponding check if ESLint doesn't pass."
    required: false
    default: false
  github-token:
    description: "GitHub token."
    required: false
    default: ${{ github.token }}
  eslint-path:
    description: "Path to the eslint binary file."
    required: false
    default: "node_modules/.bin/eslint"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "plus-square"
  color: "blue"
