name: ESLint

on:
  pull_request:
    paths-ignore: [".github/**"]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true

      - name: Install dependencies
        run: yarn install

      - uses: CatChen/eslint-suggestion-action@v1.5.12
        with:
          github-workspace: ${{ github.workspace }}
