name: ESLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, '[0-9]+-[0-9]+-*']
  workflow_run:
    workflows: ['Build']
    types:
      - completed

jobs:
  eslint:
    name: ESLint
    if: ${{ !startsWith(github.head_ref, 'workflows/tests/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true

      - name: Install dependencies
        run: yarn install

      - uses: ./
        env:
          DEBUG: 'eslint:cli-engine'
        with:
          targets: 'src/**/*'
          fail-check: ${{ github.event_name == 'workflow_run' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
